### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by jivers** [micbuffa/WebAudio-Guitar-Amplifier-Simulator#1]
I was wondering why you run a series of filters before and after the OD and general amp unit? This is very cool! I've always thought of running waveshaper -> Filter -> waveshaper -> filter. I'm just wondering what the reasons for multiple filters/types was. Kudos :)

**Comment by micbuffa** [comment]
Ahah... did you ever look at a real guitar amp schematics (look for JCM800 schematics, for example) ? Nearly all preamp stages are filters-> WS -> filters -> WS -> filters etc. the more you want gain the more WS-> filters you add. 
The github code is for the first design I've made of a guitar amp. I'm working on a new one I still haven't commited (I should do that this week I think). The clean sounds are warmer and the distorded/crunch sounds are much much better. Try https://mainline.i3s.unice.fr/AmpSim3/

**Comment by jivers** [comment]
Thanks for your response. Indeed, the ampsim 3 seems to have a series of filters and waveshapers I'm more familiar with. The band filters for quadrafuzz emulation was intriguing in v1. I was also very interested in the multiband waveshaping in version 1! Very nice implementation with bandpass filters. I've been playing around with MB compression with this technique. However, v3 actually sounds much better. Are there plans to implement multiple transfer functions into the gain stage? Anyway, question more than answered. Thanks!! Really awesome work :)

**Comment by micbuffa** [comment]
The band filters... hmmm I got the idea when I read some scientific papers about how distorsion can be achieved and about the common problems such as generating unwanted harmonics or inter-modulation when different frequencies interact together. Separating the signal into different bands is a common solution (oversampling and tricky filtering are other solutions...). So, as I wasn't building a real amp, with no constraints on costs, I said to myself: "let's try this!". And indeed, for really clean sounds, or for an acoustic simulator, or for generating metallic clean sounds (like a dobro), this is an approach I'll keep investigating. For crunch/blues/classic rock, LePou (a famous native guitar amp sim developper) gave me the advise to look closely at how classic rock amplifiers worked... He sent to me the JCM800 schematics + helped me by giving advises in emails... that's the story.

Now, what I'm going to do: complete the JCM800 inspired design with modeling the power amp stage, turn the preamp stage into a modular thing so that I can stack stages (and address the hi-gain amp problem), when the AudioWorklet node will be ready, i'll try to get a 100% accurate implementation of the tonestack (bass/medium/treble)

If you want to contribute?

I'll put on github the AmpSim3 code tomorrow I think. I'll update my readme + let you know.

BTW: thanks for your comments :-)

**Comment by jivers** [comment]
The mythical AudioWorklet :) I can’t wait any longer!!
